# Nerd Font Heavy Starship Configuration
# Full of icons, requires a Nerd Font to display properly

add_newline = true

# Format with lots of sections and icons
format = """
[┌───────────────────>](bold green)
[│](bold green)$username$hostname$directory$git_branch$git_status
[│](bold green)$package$nodejs$python$rust$golang$cmd_duration
[└─$character](bold green)"""

# Prompt character
[character]
success_symbol = "[λ](bold green)"
error_symbol = "[✗](bold red)"
vimcmd_symbol = "[V](bold green)"

# Username and hostname when SSH-ing
[username]
style_user = "bold blue"
style_root = "black bold"
format = " [$user]($style) in"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = " [$hostname](bold yellow) "
disabled = false

# Directory
[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold blue"
read_only = " "
home_symbol = "󱂵 ~"
format = "at [$path]($style)[$read_only]($read_only_style) "

# Git with lots of symbols
[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
style = "bold purple"

# Enhanced git status with counts
[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold green"
conflicted = "󰕚 "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "↕ "
untracked = "?${count} "
stashed = "*${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "

# Package version
[package]
symbol = "󰏗 "
format = "[$symbol$version]($style) "
style = "bold 208"

# Language versions
[nodejs]
symbol = " "
format = '[$symbol($version )]($style)'
style = "bold green"

[python]
symbol = " "
format = '[$symbol($version )(\($virtualenv\) )]($style)'
style = "bold yellow"

[rust]
symbol = " "
format = '[$symbol($version )]($style)'
style = "bold red"

[golang]
symbol = " "
format = '[$symbol($version )]($style)'
style = "bold cyan"

# Command duration
[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow) "

# Time
[time]
disabled = false
format = "[$time](bold cyan) "
time_format = "%T" 